### PR TITLE
fix: missing node-fetch in package.json

### PR DESCRIPTION
**Pull request by wyhao31**
The module was introduced in https://github.com/hangwin/mcp-chrome/commit/15fe6df7685e130a9430736487bbc3bf7ef9499b.

Build error:
```
src/file-handler.ts(5,19): error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.
```

I added the package by running:
```
pnpm --filter mcp-chrome-bridge add node-fetch@3
```

### CODE REVIEW

**Comment by wyhao31** [comment]
It turns out we cannot use `node-fetch@3` because it's not compatible with CommonJS.
